update deployment

diff --git a/bin/docker-postpublish b/bin/docker-postpublish
--- a/bin/docker-postpublish
+++ b/bin/docker-postpublish
@@ -1,14 +1,16 @@
 #!/bin/bash
 set -e
-trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
-trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
 
 azure_cr_domain=azurecr.io
 
 tmp=$1
 image_digest=$2
 
-echo "Got digest ${image_digest}"
+deploy_failed() {
+    echo "Deploy failed."
+
+    exit 1
+}
 
 find_repo() {
     repo=$1
@@ -36,31 +38,27 @@ if [[ ! -z "${CONTAINER_REGISTER_URL}" ]] && [[ $CONTAINER_REGISTER_URL == *"${a
         find_repo_ecode=$?
         
         if [ $find_repo_ecode -eq 0 ]; then
-            echo "Got list of repos..."
-
             repo_manifests=$(az acr repository show-manifests -n $CONTAINER_REGISTER_NAME --repository $reg_repo --top 10 --orderby time_desc)
-            echo "Got list of manifests..."
+
             ml="${tmp}/manifests.txt"
             echo "${repo_manifests}" >> $ml
             ml_a=$(realpath $ml)
+
             ${BASH_SOURCE%/*}/acr-helpers/manifests.py --manifests "${ml_a}" --digest "${image_digest}"
             found_manifest=$?
             
             if [[ $found_manifest -eq 0 ]]; then
-                echo "Deploy successful!"
                 exit 0
             else
-                echo "Deploy failed."
-                exit 1
+                deploy_failed
             fi
         else
-            echo "Failed."
-            exit 1
+            deploy_failed
         fi
     else
         echo "Azure CLI doesn't seem to be installed/in PATH. Assuming successful deployment."
         exit 0
     fi
 else
-    echo "Idk."
+    echo "Not implemented. Assuming successful deployment."
 fi
diff --git a/bin/docker-publish b/bin/docker-publish
--- a/bin/docker-publish
+++ b/bin/docker-publish
@@ -1,11 +1,30 @@
 #!/bin/bash
 set -e
-trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
-trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
 
 tmp_id=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')
 tmp="tmp_${tmp_id}"
 mkdir $tmp
+
+last_ec=0
+before_exit_clean=0
+before_exit_run=0
+
+cleanup() {
+    rm -rf "${tmp}/"
+}
+
+before_exit() {
+    if [[ $before_exit_run -ne 0 ]]; then
+        echo "Cleaning up after failure..."
+        cleanup
+
+        before_exit_run=1
+    fi
+}
+
+trap 'last_ec=$?;before_exit' EXIT
+
+#exit 1
 
 LOG_FILE="${tmp}/log.txt"
 
@@ -22,8 +41,6 @@ fi
 iname=${IMAGE_NAME:-image}
 iversion=${IMAGE_VERSION:-latest}
 
-idig="" # empty on purpose
-
 if [[ ! -z "${CONTAINER_REGISTER_URL}" ]]; then
     echo "Tagging $iname:$iversion at $CONTAINER_REGISTER_URL..."
     echo $(docker tag $iname $CONTAINER_REGISTER_URL/$iname:$iversion)
@@ -39,8 +56,6 @@ if [[ ! -z "${CONTAINER_REGISTER_URL}" ]]; then
     docker push $CONTAINER_REGISTER_URL/$iname:$iversion | tee $DP_LOG_FILE
 
     idig=$(${BASH_SOURCE%/*}/acr-helpers/get-deploy-digest $DP_LOG_FILE)
-
-    echo "${idig}"
 else
     echo "Pushing $iname:$iversion..."
     
@@ -49,7 +64,7 @@ fi
 
 bin/docker-postpublish $tmp $idig
 
-rm -rf "${tmp}/"
+cleanup
 
 echo "Done."
 
